@app_productoAPI_HostAddress = http://localhost:5212

GET {{app_productoAPI_HostAddress}}/weatherforecast/
Accept: application/json

###
GET {{app_productoAPI_HostAddress}}/api/producto/
Accept: application/json

###
GET {{app_productoAPI_HostAddress}}/api/producto/8
Accept: application/json
